### ISSUE TITLE
Athena interface does not build / can not find get_comm_world 

### ISSUE THREAD

**Issue by christianboily** [amusecode/amuse#1100]
**Describe the bug**
The community code Athena is a grid hydro solver working in 2D/3D : the amuse interface (4.0.1) does not compile 

**To Reproduce**
$(AMUSEDIR)/make athena.code DOWNLOAD_CODES=0 

**Expected behavior**
Should recover at least a one-processor worker in the community/athena directory/

**Logs**
mpicc -g -O2 -fno-common -g -O2 -fno-common -DAMUSE -g    -Ibuild/src -I/opt/work/cmb/Amuse/Amuse_15.2/amuse-source//lib/stopcond -c -o build/interface_4.1.o interface_4.1.c 
interface_4.1.c: In function 'initialize_code':
interface_4.1.c:403:5: error: implicit declaration of function 'get_comm_world' [-Wimplicit-function-declaration]

**Environment (please complete the following information):**
Compiler : mpicc = gcc-mp-14 (MacPorts gcc14 14.2.0_3+stdlib_flag) 14.2.0  

OS : @ OSX 15.2 (Sequoia)

**Additional context**
Every other sub-code compiles and in fact the whole package compiled just fine last summer (OSX Somosa 14.7) and 
that seems to do with newer mpi scripts at McPorts ? Most (5/6) libraries compile on my installation (not Saporo, no GPU)
and about 46 of 52 codes. Not Athena sadly.

**Comment by LourensVeen** [comment]
Hi Christian,

You're absolutely right that things aren't working as well as we'd like for them to. I've been working on fixing the AMUSE build system (https://github.com/amusecode/amuse/issues/1024) and the various codes and I'm approaching a new release with many fixes, including a bunch for Athena.

You could try to backport some of those (they're on this branch: https://github.com/LourensVeen/amuse/tree/convert-athena), but there are also some major changes to the whole setup, so that may take a bit of effort.

Alternatively, that new release should be in the near future, assuming that things that were previously fixed don't suddenly break again, like MESA did the other day. A couple weeks, hopefully.

**Comment by christianboily** [comment]
Hey Laurens, thanks a lot for the feedback, am sure this is a lot of work and don't mean to apply extra pressure so let's take things in stride and appreciate that many codes & setups do seem to work 😉 I am testing gadget, phantom, ph4, ..so far so good. I'll look up the link you suggested, thanks! 

All the best, bye, Chris b.


----- Mail d’origine -----
De: Lourens Veen ***@***.***>
À: amusecode/amuse ***@***.***>
Cc: christian boily ***@***.***>, Author ***@***.***>
Envoyé: Wed, 15 Jan 2025 16:25:45 +0100 (CET)
Objet: Re: [amusecode/amuse] Athena interface does not build / can not find get_comm_world  (Issue #1100)

Hi Christian,

You're absolutely right that things aren't working as well as we'd like for them to. I've been working on fixing the AMUSE build system (https://github.com/amusecode/amuse/issues/1024) and the various codes and I'm approaching a new release with many fixes, including a bunch for Athena.

You could try to backport some of those (they're on this branch: https://github.com/LourensVeen/amuse/tree/convert-athena), but there are also some major changes to the whole setup, so that may take a bit of effort.

Alternatively, that new release should be in the near future, assuming that things that were previously fixed don't suddenly break again, like MESA did the other day. A couple weeks, hopefully.
